# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum_detail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=10)),
                ('name', models.TextField()),
                ('point', models.FloatField()),
                ('type', models.IntegerField()),
                ('class_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum_index',
            fields=[
                ('college_num', models.IntegerField()),
                ('year', models.IntegerField()),
                ('college', models.TextField()),
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('score_pub', models.FloatField()),
                ('score_core', models.FloatField()),
                ('score_sele', models.FloatField()),
                ('score_dev', models.FloatField()),
                ('ps', models.TextField(null=True)),
            ],
        ),
    ]
