# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_auto_20170619_1930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='Major',
        ),
    ]
