# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_delete_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('term', models.IntegerField()),
                ('number', models.CharField(max_length=10)),
                ('name', models.TextField()),
                ('type_c', models.CharField(max_length=5)),
                ('point', models.FloatField()),
                ('get_point', models.FloatField()),
                ('grade', models.CharField(max_length=3)),
                ('gpa', models.FloatField()),
                ('gpa_t', models.FloatField()),
                ('type', models.IntegerField()),
                ('stu_num', models.IntegerField()),
                ('class_num', models.IntegerField()),
            ],
        ),
    ]
