# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0007_auto_20170621_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='if_complete',
            field=models.BooleanField(default=0),
        ),
    ]
