# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0008_detail_if_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorScore',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lesson_num', models.CharField(max_length=10)),
                ('lesson_name', models.TextField()),
                ('point', models.FloatField()),
                ('type', models.IntegerField()),
                ('class_num', models.IntegerField()),
                ('stu_num', models.IntegerField()),
                ('grade', models.CharField(max_length=3)),
                ('if_complete', models.BooleanField(default=0)),
            ],
        ),
    ]
