# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0009_majorscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='stu_name',
            field=models.CharField(default='na', max_length=10),
            preserve_default=False,
        ),
    ]
